# Generated by Django 2.0.9 on 2018-11-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('Horror', 'Horror'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('SciFi', 'SciFi'), ('Action', 'Action'), ('Period', 'Period')], max_length=10)),
            ],
        ),
    ]
